### PR TITLE
Possibility to switch between remote and local shell run

### PR DESCRIPTION
**Pull request by ytsarev**
Remote is default as it is standard kitchen behavior

### CODE REVIEW

**Comment by sawanoboly** [comment]
Is this works correctly?

I seem that we must use instance.transport in `#call` to run command remotely.

**Comment by sawanoboly** [comment]
And, I'll refuse to make the remote by default.

**Comment by ytsarev** [comment]
@sawanoboly  it does work, though i find it strange. #call seems not to be properly overridden in my tests/environment, so original Base#call is in action. I will double check.
Regarding default behavior  - have no trouble with that and will reverse the logic.

**Comment by sawanoboly** [comment]
I cannot understand clearly, why it works..

I think that it should use transport.connection below to switch location.
Is this what you mean?

```
...
      default_config :enter_instance, false

      # (see Base#call)
      def call(state)
        info("[#{name}] Verify on instance=#{instance} with state=#{state}")
        sleep_if_set
        merge_state_to_env(state)

        if config[:enter_instance]
          instance.transport.connection(state) do |conn|
            conn.execute(config[:command])
          end
        else
          shellout
        end
        debug("[#{name}] Verify completed.")
      end
...
```

**Comment by ytsarev** [comment]
First of all, I realized that Shell#call is never getting called for some reason.

**Comment by ytsarev** [comment]
Dug it a bit. 

In instance.rb

```
    # Perform the verify action.                                                
    #                                                                           
    # @see Driver::Base#verify                                                  
    # @return [self] this instance, used to chain actions                       
    # @api private                                                              
    def verify_action                                                           
      banner "Verifying #{to_str}..."                                           
      elapsed = action(:verify) do |state|                                      
        if legacy_ssh_base_driver?                                              
          legacy_ssh_base_verify(state)                                         
        else                                                                    
          verifier.call(state)                                                  
        end                                                                     
      end                                                                       
      info("Finished verifying #{to_str} #{Util.duration(elapsed.real)}.")      
      self                                                                      
    end
```

And that's exactly my setup with kitchen-docker:

```
kitchen verify
-----> Starting Kitchen (v1.4.1)
-----> Setting up <default-fake>...
$$$$$$ Running legacy setup for 'Docker' Driver
```

So in that case #call is ironically never called

**Comment by ytsarev** [comment]
So i will probably get kitchen-docker to better state first, then return with updated PR

**Pull request closed without merging**
